name: ci
on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: make fmt
        uses: ./ci/image
        with:
          args: make fmt

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: make lint
        uses: ./ci/image
        with:
          args: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: make test
        uses: ./ci/image
        with:
          args: make test
        env:
          COVERALLS_TOKEN: ${{ secrets.github_token }}
      - name: Upload coverage.html
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: ci/out/coverage.html
